export const API_LOCAL = "http://localhost:5000"
export const API_1 = "https://excited-frog-stockings.cyclic.app"
// export const API = process.env.NODE_ENV === 'production' ? "https://server-code-vphw.onrender.com" : "http://localhost:5000"
export const API = process.env.NODE_ENV === 'production' ? "https://fair-teal-hippo-hat.cyclic.app" : "http://localhost:5000"
// export const API = "https://server-code-vphw.onrender.com"